# Generated by Django 4.2.5 on 2023-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0002_alter_phone_image_alter_phone_name_alter_phone_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="phone",
            name="name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="phone",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="phone",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
